#!/bin/sh

while true
  do
    MEMORY=" $(free -m | grep '^Mem' | awk '{printf("%.2f%", $3/$2*100)}')%"
    CPU=" $(top -b -n1 | grep ^%Cpu | awk '{printf("%.2f%%"), 100-$8}')"

    VOLUME_INDICATOR="$(if [ $(pacmd list-sinks | awk 'BEGIN { FS=":" } /muted:/ {print $2}') = "yes" ]; then echo "ﱝ"; else; echo ""; fi)"
    VOLUME="$VOLUME_INDICATOR $(pacmd list-sinks | awk 'BEGIN { FS="/" } /front-left:/ {print $2}' | xargs)"

    BATTERY=" $(cat /sys/class/power_supply/BAT0/capacity)%"

    DATE="$( date +"%a, %b %d %R" )"
    
    xsetroot -name "$MEMORY | $CPU | $VOLUME | $BATTERY | $DATE"
    sleep 1s
done &
feh --bg-fill --randomize ~/Wallpapers/* &
while true;  do  /usr/local/bin/dwm > /dev/null; done;
