#!/bin/sh

while true
  do
    MEMORY=" $(free -m | grep '^Mem' | awk '{printf("%.2f%", $3/$2*100)}')%"
    CPU=" $(top -b -n1 | grep ^%Cpu | awk '{printf("%.2f%%"), 100-$8}')"
    BATTERY=" $(cat /sys/class/power_supply/BAT0/capacity)%"
    DATE="$( date +"%a, %b %d %R" )"
    
    xsetroot -name "$MEMORY | $CPU | $BATTERY | $DATE"
    sleep 1s
done &
feh --bg-fill --randomize ~/Wallpapers/* &
while true;  do  /usr/local/bin/dwm > /dev/null; done;
